services:
  redis:
    image: redis:7-alpine
    container_name: redis_backend
    restart: unless-stopped

  api:
    build: .
    container_name: fastapi_redis_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis